import mongoose, { Schema } from "mongoose"

const recipe = new Schema({
	// ID autogenerated
	recipe_name: String,
	ingredients: [],
	description: String,
	created_by: String,
})

const model = mongoose.model("Recipe", recipe)

export const schema = model.schema
export default model
